name: Enforce PR from Pre-Prod to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print Source and Target Branch
        run: |
          echo "Target Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Source Branch: ${{ github.event.pull_request.head.ref }}"
      - name: Check if PR is from Pre-Prod
        if: github.event.pull_request.head.ref != 'Pre-Prod'
        run: |
          echo "❌ Pull requests to 'main' must originate from 'Pre-Prod' branch."
          exit 1
